-- 세영님
CREATE TABLE MEMBER(
    MEMBER_NUM NUMBER(20) CONSTRAINT PK_PROJECT PRIMARY KEY,   -- ���
    MEMBER_NAME VARCHAR2(20) NOT NULL,  -- �̸�
	DIV_NAME    VARCHAR2(20) NOT NULL,  -- �μ��̸�
    RANK        VARCHAR2(20) NOT NULL,  -- ����
    ADDRESS     VARCHAR2(80),           -- �ּ�
    PHONE       VARCHAR2(20),           -- ��ȭ��ȣ
    MAIL        VARCHAR2(20),           -- ����
    HIRE_DATE   VARCHAR2(20) NOT NULL,  -- �Ի���
    RETIRE_DATE VARCHAR2(20),           -- �����
    SSN         VARCHAR2(20) NOT NULL,  -- �ֹι�ȣ
    PASSWORD    VARCHAR2(20) NOT NULL,  -- ��й�ȣ
    GENDER      VARCHAR2(20),           -- ����
    PHOTO       VARCHAR2(20),           -- ����
    ANNUAL_LEAVE NUMBER(20) DEFAULT 20
);

CREATE TABLE ATTENDANCE(
    ATT_NO NUMBER(20) NOT NULL CONSTRAINT PK_ATTENDANCE PRIMARY KEY,
    MEMBER_NUM  NUMBER(20) NOT NULL 
                CONSTRAINT ATTENDANCE_MEMBER_NO_FK REFERENCES MEMBER(MEMBER_NUM),-- �ܷ�Ű ����
	ATT_DATE    DATE DEFAULT SYSDATE,
    ATT_START   VARCHAR2(80),
    ATT_FIN     VARCHAR2(80),
    ATT_TOTAL   NUMBER,
    ATT_STATUS  VARCHAR2(80)
) ;

-- 경진님
--회의실 예약
CREATE TABLE MEETING_ROOM 
(
  MEMBER_NUM NUMBER(20) NOT NULL 
, MEETING_NO VARCHAR2(50) --회의실no
, MEETING_DATE VARCHAR2(20) NOT NULL --회의날짜
, MEETING_TIME VARCHAR2(20) NOT NULL --회의시간
, RESERVATION VARCHAR2(20) --예약여부
);

COMMENT ON COLUMN MEETING_ROOM.RESERVATION IS '0:예약취소/1:예약';

--채팅방 생성
CREATE TABLE CHATROOM 
(
  CHATROOM_NO NUMBER NOT NULL --채팅방no
, CHATROOM_TITLE VARCHAR2(60 BYTE) --방제
, CHATROOM_TYPE NUMBER --1:1/1:N
, CONSTRAINT CHATROOM_PK PRIMARY KEY 
  (
    CHATROOM_NO 
  )
);
COMMENT ON COLUMN CHATROOM.CHATROOM_TYPE IS '1:1/1:N';

--채팅멤버

CREATE TABLE CHAT_MEMBER 
(
  CHATROOM_NO NUMBER 
, MEMBER_NUM NUMBER(20, 0) NOT NULL 
, DIV_NAME VARCHAR2(20 BYTE)
, MEMBER_NAME VARCHAR2(20 BYTE) 
, RANK VARCHAR2(20 BYTE) 
, MEMBER_STATUS VARCHAR2(20 BYTE) DEFAULT 0 --채팅방 나감/안나감
); 

COMMENT ON COLUMN CHAT_MEMBER.MEMBER_STATUS IS '나감/안나감';

CREATE TABLE CHAT_CONTENT 
(
  CHAT_CONTENT_NO NUMBER NOT NULL --채팅내용번호
, CHATROOM_NO NUMBER NOT NULL --방no
, CHAT_CONTENT VARCHAR2(20 BYTE)  --채팅내용
, MEMBER_NUM NUMBER(20, 0) NOT NULL
, CAHT_DATE DATE DEFAULT SYSDATE NOT NULL --채팅날짜 
, CONSTRAINT CHAT_CONTENT_PK PRIMARY KEY 
  (
    CHAT_CONTENT_NO 
  )
);

-- 승찬님
--------------------------------------------------------
--  DDL for Table MAIL
--------------------------------------------------------

  CREATE TABLE "PROJECT"."MAIL" 
   (	"MAIL_NUM" NUMBER, 
	"MAIL_TITLE" VARCHAR2(100 BYTE), 
	"MAIL_CONTENT" VARCHAR2(500 BYTE) DEFAULT '�������', 
	"MAIL_SENDER" VARCHAR2(30 BYTE), 
	"MAIL_FROM_DATE" DATE, 
	"MAIL_TO_DATE" DATE DEFAULT SYSDATE, 
	"MAIL_REFEREE" VARCHAR2(20 BYTE) DEFAULT SYSDATE, 
	"REF_NUM" NUMBER, 
	"MAIL_RECEIVER" VARCHAR2(50 BYTE), 
	"REC_NUM" NUMBER, 
	"REC_STATUS" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"MAIL_FILENUM" NUMBER, 
	"MAIL_FILENAME" VARCHAR2(20 BYTE), 
	"MAIL_FILEPATH" VARCHAR2(500 BYTE), 
	"MEMBER_NUM" NUMBER, 
	"MAIL_FILERENAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MAIL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT"."MAIL_PK" ON "PROJECT"."MAIL" ("MAIL_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table MAIL
--------------------------------------------------------

  ALTER TABLE "PROJECT"."MAIL" MODIFY ("MAIL_NUM" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."MAIL" MODIFY ("MAIL_TITLE" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."MAIL" MODIFY ("MAIL_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."MAIL" MODIFY ("MAIL_SENDER" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."MAIL" MODIFY ("MAIL_FROM_DATE" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."MAIL" MODIFY ("MAIL_TO_DATE" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."MAIL" MODIFY ("REC_NUM" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."MAIL" MODIFY ("MEMBER_NUM" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."MAIL" ADD CONSTRAINT "MAIL_PK" PRIMARY KEY ("MAIL_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MAIL
--------------------------------------------------------

  ALTER TABLE "PROJECT"."MAIL" ADD CONSTRAINT "MAIL_MEMBER_MEMBERNUM_FK" FOREIGN KEY ("MEMBER_NUM")
	  REFERENCES "PROJECT"."MEMBER" ("MEMBER_NUM") ENABLE;

-- 주형님
--------------------------------------------------------
--  DDL for Table FILE_BOARD
--------------------------------------------------------

  CREATE TABLE "PROJECT"."FILE_BOARD" 
   (	"FILE_BOARD_NO" NUMBER, 
	"MEMBER_NUM" VARCHAR2(50 BYTE), 
	"FILE_BOARD_DATE" DATE DEFAULT SYSDATE, 
	"FILE_BOARD_TITLE" VARCHAR2(50 BYTE), 
	"FILE_BOARD_CONTENT" VARCHAR2(50 BYTE), 
	"FILE_BOARD_VIEW" NUMBER, 
	"FILE_NAME" VARCHAR2(50 BYTE), 
	"FILE_RENAME" VARCHAR2(50 BYTE), 
	"FILE_PATH" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "PROJECT"."FILE_BOARD"."FILE_BOARD_NO" IS '자료게시글번호';
   COMMENT ON COLUMN "PROJECT"."FILE_BOARD"."MEMBER_NUM" IS '사원번호';
   COMMENT ON COLUMN "PROJECT"."FILE_BOARD"."FILE_BOARD_DATE" IS '자료작성날짜';
   COMMENT ON COLUMN "PROJECT"."FILE_BOARD"."FILE_BOARD_TITLE" IS '자료제목';
   COMMENT ON COLUMN "PROJECT"."FILE_BOARD"."FILE_BOARD_CONTENT" IS '자료본문';
   COMMENT ON COLUMN "PROJECT"."FILE_BOARD"."FILE_BOARD_VIEW" IS '자료조회수';
   COMMENT ON COLUMN "PROJECT"."FILE_BOARD"."FILE_NAME" IS '원본파일이름';
   COMMENT ON COLUMN "PROJECT"."FILE_BOARD"."FILE_RENAME" IS '재설정파일이름';
   COMMENT ON COLUMN "PROJECT"."FILE_BOARD"."FILE_PATH" IS '파일경로';
REM INSERTING into PROJECT.FILE_BOARD
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index FILE_BOARD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT"."FILE_BOARD_PK" ON "PROJECT"."FILE_BOARD" ("FILE_BOARD_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table FILE_BOARD
--------------------------------------------------------

  ALTER TABLE "PROJECT"."FILE_BOARD" ADD CONSTRAINT "FILE_BOARD_PK" PRIMARY KEY ("FILE_BOARD_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROJECT"."FILE_BOARD" MODIFY ("FILE_PATH" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."FILE_BOARD" MODIFY ("FILE_RENAME" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."FILE_BOARD" MODIFY ("FILE_NAME" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."FILE_BOARD" MODIFY ("FILE_BOARD_VIEW" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."FILE_BOARD" MODIFY ("FILE_BOARD_DATE" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."FILE_BOARD" MODIFY ("FILE_BOARD_NO" NOT NULL ENABLE);

-- 푸름님
--------- 1. 문서 양식
CREATE TABLE APP_FORM
(
    FORM_NO  NUMBER CONSTRAINT APP_FORM_FORM_NO_PK PRIMARY KEY,  -- 문서양식 번호
    FORM_NAME  VARCHAR2(100) NOT NULL, -- 문서양식 명
    FORM_CONTENT CLOB  -- 문서양식 내용
);



--------- 2. 기안 문서
CREATE TABLE APP_DOC
(
    DOC_NO        NUMBER CONSTRAINT APP_DOC_DOC_NO_PK PRIMARY KEY, --문서번호
    MEMBER_NUM NUMBER(20, 0) NOT NULL, --사원번호
    FORM_NO       NUMBER NOT NULL, --문서 양식번호
    DOC_TITLE     VARCHAR2(100) NOT NULL, --문서제목
    DOC_CONTENT   CLOB, --내용
    DOC_STATUS    VARCHAR2(10) DEFAULT '대기'  NOT NULL, --진행 상태(대기, 완료 등)
    DOC_DATE      VARCHAR2(50) NOT NULL, --작성일
    LEAVE_TYPE    VARCHAR2(50), --휴가 종류
    LEAVE_START   VARCHAR2(50), --휴가 시작일
    LEAVE_END     VARCHAR2(50), --휴가 종료일 
    LEAVE_TIME    VARCHAR2(10), --반차 시간
    LEAVE_DATE    NUMBER, --휴가 일수
    LEAVE_LEFT    NUMBER, --잔여 연차 일수
    LEAVE_APPLY   NUMBER, --연차 신청일
    CONSTRAINT APP_DOC_MEMBER_NUM_FK FOREIGN KEY (MEMBER_NUM) REFERENCES MEMBER(MEMBER_NUM),
    CONSTRAINT APP_DOC_FORM_NO_FK FOREIGN KEY (FORM_NO) REFERENCES APP_FORM(FORM_NO)
);


--------- 3. 파일 첨부
CREATE TABLE APP_FILE
(
    FILE_NO      NUMBER CONSTRAINT APP_FILE_FILE_NO_PK PRIMARY KEY, --파일 번호
    DOC_NO       NUMBER NOT NULL, --문서 번호
    FILE_NAME    VARCHAR2(1000) NOT NULL, --원본 파일명
    FILE_RENAME  VARCHAR2(1000) NOT NULL, --수정 파일명
    FILE_PATH    VARCHAR2(1000) NOT NULL, --파일 경로
    CONSTRAINT APP_FILE_DOC_NO_FK FOREIGN KEY (DOC_NO) REFERENCES APP_DOC(DOC_NO)
);


--------- 4. 참조
CREATE TABLE APP_REF
(
    REF_NO       NUMBER CONSTRAINT APP_REF_REF_NO_PK PRIMARY KEY, --참조 번호
    DOC_NO       NUMBER NOT NULL, --문서 번호
    MEMBER_NUM  NUMBER(20, 0) NOT NULL, --사원번호
    REF_STATUS   VARCHAR2(20) NOT NULL, --참조 상태
    CONSTRAINT APP_REF_DOC_NO_FK FOREIGN KEY (DOC_NO) REFERENCES APP_DOC(DOC_NO),
    CONSTRAINT APP_REF_MEMBER_NUM_FK FOREIGN KEY (MEMBER_NUM) REFERENCES MEMBER(MEMBER_NUM)
);

--------- 5. 전자 결재
CREATE TABLE APPROVAL (
    APP_NO     NUMBER CONSTRAINT APPROVAL_APP_NO_PK PRIMARY KEY, --결재 번호
    DOC_NO     NUMBER NOT NULL, --문서 번호
    MEMBER_NUM  NUMBER(20, 0) NOT NULL, --사원 번호
    APP_LEVEL  NUMBER NOT NULL, --결재 순서
    APP_DATE   VARCHAR2(50), -- 결재일
    APP_STATUS VARCHAR2(20) DEFAULT '대기' NOT NULL, --결재 상태
    REJ_REASON VARCHAR2(20), --반려 사유
    CONSTRAINT APPROVAL_DOC_NO_FK FOREIGN KEY (DOC_NO) REFERENCES APP_DOC(DOC_NO),
    CONSTRAINT APPROVAL_MEMBER_NUM_FK FOREIGN KEY (MEMBER_NUM) REFERENCES MEMBER(MEMBER_NUM)
);


--------- 시퀀스 
create sequence seq_ref; -- 참조 번호
create sequence seq_form;  -- 문서 양식 번호
create sequence seq_app; -- 결재 번호
create sequence seq_doc; -- 문서 번호
create sequence seq_file; -- 파일 번호

-- 예솔님
-- 공지사항 게시판
CREATE TABLE NOTICE (
	NOTICE_NUM NUMBER(20) PRIMARY KEY, --공지게시글번호
	MEMBER_NUM NUMBER(20) NOT NULL, --사번
	TITLE NVARCHAR2(255) NOT NULL, --제목
	CONTENT NVARCHAR2(1023) NOT NULL, --본문
	VIEWS NUMBER(10) NOT NULL, --조회수
    	CREATED_AT DATE NOT NULL --작성일
);

CREATE SEQUENCE NOTICE_SEQ;

-- 자유 게시판

CREATE TABLE COMMUNITY (
	COM_NUM NUMBER(20) PRIMARY KEY NOT NULL, --자유게시글번호
	MEMBER_NUM NUMBER(20) NOT NULL, --사번
	COM_TITLE NVARCHAR2(255) NOT NULL, --제목
	COM_CONTENT NVARCHAR2(1023) NOT NULL, --본문
	COM_VIEWS NUMBER(10), --조회수
	COM_CREATED_AT DATE --작성일
);

CREATE SEQUENCE COMMUNITY_SEQ;

-- 자유 게시판 댓글
CREATE TABLE REPLY (
	REPLY_NUM NUMBER(20) PRIMARY KEY NOT NULL, --댓글번호
	MEMBER_NUM NUMBER(20) NOT NULL, --사번
	COM_NUM NUMBER(20) NOT NULL, --자유게시글번호
	PARENT_REPLY_NUM NUMBER(20), --부모댓글번호
	REPLY_CONTENT NVARCHAR2(511) NOT NULL, --댓글
	REPLY_CREATED_AT DATE --댓글작성일
);

CREATE SEQUENCE REPLY_SEQ;
